// Overlay HUD font helpers — metrics generated by bake_overlay_font.
#include "overlay_font_metrics.glsl"

int overlayCharIndex(int codepoint)
{
    if (codepoint >= 65 && codepoint <= 90) {
        return codepoint - 65;
    }
    if (codepoint >= 97 && codepoint <= 122) {
        return codepoint - 97;
    }
    return -1;
}

float sampleGlyphAlpha(vec2 local, int glyphIndex)
{
    if (glyphIndex < 0 || glyphIndex >= 26) {
        return 0.0;
    }
    OverlayGlyph g = kOverlayGlyphs[glyphIndex];
    vec2 size = vec2(g.uv.z - g.uv.x, g.uv.w - g.uv.y);
    vec2 atlasSize = vec2(512.0, 64.0);
    size *= atlasSize;
    if (local.x < 0.0 || local.y < 0.0 || local.x >= size.x || local.y >= size.y) {
        return 0.0;
    }
    vec2 uv = mix(g.uv.xy, g.uv.zw, (local + 0.5) / size);
    return texture(uFontAtlas, uv).a;
}

float drawGlyph(vec2 p, inout vec2 cursor, float scale, int codepoint)
{
    int idx = overlayCharIndex(codepoint);
    if (idx < 0) {
        return 0.0;
    }
    OverlayGlyph g = kOverlayGlyphs[idx];
    vec2 size = vec2(g.uv.z - g.uv.x, g.uv.w - g.uv.y) * vec2(512.0, 64.0) * scale;
    vec2 local = (p - cursor) / scale;
    float alpha = sampleGlyphAlpha(local, idx);
    cursor.x += g.advance * scale;
    return alpha;
}

float drawLabelRow(vec2 p, vec2 origin, float scale, int row)
{
    vec2 cursor = origin;
    float alpha = 0.0;
    if (row == 0) {
        alpha = max(alpha, drawGlyph(p, cursor, scale, 73)); // I
        alpha = max(alpha, drawGlyph(p, cursor, scale, 78)); // N
        alpha = max(alpha, drawGlyph(p, cursor, scale, 84)); // T
        alpha = max(alpha, drawGlyph(p, cursor, scale, 69)); // E
        alpha = max(alpha, drawGlyph(p, cursor, scale, 78)); // N
        alpha = max(alpha, drawGlyph(p, cursor, scale, 83)); // S
        alpha = max(alpha, drawGlyph(p, cursor, scale, 73)); // I
        alpha = max(alpha, drawGlyph(p, cursor, scale, 84)); // T
        alpha = max(alpha, drawGlyph(p, cursor, scale, 89)); // Y
        return alpha;
    }
    if (row == 1) {
        alpha = max(alpha, drawGlyph(p, cursor, scale, 83)); // S
        alpha = max(alpha, drawGlyph(p, cursor, scale, 72)); // H
        alpha = max(alpha, drawGlyph(p, cursor, scale, 65)); // A
        alpha = max(alpha, drawGlyph(p, cursor, scale, 80)); // P
        alpha = max(alpha, drawGlyph(p, cursor, scale, 69)); // E
        return alpha;
    }
    if (row == 2) {
        alpha = max(alpha, drawGlyph(p, cursor, scale, 83)); // S
        alpha = max(alpha, drawGlyph(p, cursor, scale, 84)); // T
        alpha = max(alpha, drawGlyph(p, cursor, scale, 82)); // R
        alpha = max(alpha, drawGlyph(p, cursor, scale, 69)); // E
        alpha = max(alpha, drawGlyph(p, cursor, scale, 84)); // T
        alpha = max(alpha, drawGlyph(p, cursor, scale, 67)); // C
        alpha = max(alpha, drawGlyph(p, cursor, scale, 72)); // H
        return alpha;
    }
    if (row == 3) {
        alpha = max(alpha, drawGlyph(p, cursor, scale, 70)); // F
        alpha = max(alpha, drawGlyph(p, cursor, scale, 76)); // L
        alpha = max(alpha, drawGlyph(p, cursor, scale, 79)); // O
        alpha = max(alpha, drawGlyph(p, cursor, scale, 79)); // O
        alpha = max(alpha, drawGlyph(p, cursor, scale, 82)); // R
        return alpha;
    }
    if (row == 4) {
        alpha = max(alpha, drawGlyph(p, cursor, scale, 67)); // C
        alpha = max(alpha, drawGlyph(p, cursor, scale, 79)); // O
        alpha = max(alpha, drawGlyph(p, cursor, scale, 76)); // L
        alpha = max(alpha, drawGlyph(p, cursor, scale, 79)); // O
        alpha = max(alpha, drawGlyph(p, cursor, scale, 82)); // R
        return alpha;
    }
    alpha = max(alpha, drawGlyph(p, cursor, scale, 83)); // S
    alpha = max(alpha, drawGlyph(p, cursor, scale, 77)); // M
    alpha = max(alpha, drawGlyph(p, cursor, scale, 79)); // O
    alpha = max(alpha, drawGlyph(p, cursor, scale, 79)); // O
    alpha = max(alpha, drawGlyph(p, cursor, scale, 84)); // T
    alpha = max(alpha, drawGlyph(p, cursor, scale, 72)); // H
    return alpha;
}
