// Build-time tool: bake DejaVu Sans A–Z into an RGBA atlas + GLSL glyph metrics.
#include <cmath>
#include <cstdio>
#include <cstring>
#include <filesystem>
#include <fstream>
#include <string>
#include <vector>

#define STB_TRUETYPE_IMPLEMENTATION
#include "stb_truetype.h"

namespace {

constexpr int kAtlasWidth = 512;
constexpr int kAtlasHeight = 64;
constexpr float kFontSize = 18.0f;
constexpr int kGlyphCount = 26;

struct GlyphRect {
    int x0 = 0;
    int y0 = 0;
    int x1 = 0;
    int y1 = 0;
    float advance = 0.0f;
};

bool writeAtlasHeader(const std::filesystem::path &path, const std::vector<uint8_t> &pixels)
{
    std::ofstream out(path);
    if (!out) {
        return false;
    }
    out << "#pragma once\n\n";
    out << "namespace AutoHdrVk {\n\n";
    out << "inline constexpr uint32_t kOverlayFontAtlasWidth = " << kAtlasWidth << "u;\n";
    out << "inline constexpr uint32_t kOverlayFontAtlasHeight = " << kAtlasHeight << "u;\n";
    out << "inline constexpr uint8_t kOverlayFontAtlasRgba[] = {\n";
    for (size_t i = 0; i < pixels.size(); ++i) {
        if (i % 16 == 0) {
            out << "    ";
        }
        out << static_cast<int>(pixels[i]);
        if (i + 1 < pixels.size()) {
            out << ", ";
        }
        if (i % 16 == 15) {
            out << "\n";
        }
    }
    if (pixels.size() % 16 != 0) {
        out << "\n";
    }
    out << "};\n\n";
    out << "} // namespace AutoHdrVk\n";
    return true;
}

bool writeMetricsGlsl(const std::filesystem::path &path, const GlyphRect glyphs[kGlyphCount])
{
    std::ofstream out(path);
    if (!out) {
        return false;
    }
    out << "// Generated by bake_overlay_font — do not edit.\n";
    out << "struct OverlayGlyph {\n";
    out << "    vec4 uv;     // u0, v0, u1, v1\n";
    out << "    float advance;\n";
    out << "};\n\n";
    out << "const OverlayGlyph kOverlayGlyphs[26] = OverlayGlyph[](\n";
    for (int i = 0; i < kGlyphCount; ++i) {
        const GlyphRect &g = glyphs[i];
        const float u0 = static_cast<float>(g.x0) / static_cast<float>(kAtlasWidth);
        const float v0 = static_cast<float>(g.y0) / static_cast<float>(kAtlasHeight);
        const float u1 = static_cast<float>(g.x1) / static_cast<float>(kAtlasWidth);
        const float v1 = static_cast<float>(g.y1) / static_cast<float>(kAtlasHeight);
        out << "    OverlayGlyph(vec4(" << u0 << ", " << v0 << ", " << u1 << ", " << v1 << "), "
            << g.advance << "f)";
        out << (i + 1 < kGlyphCount ? ",\n" : "\n");
    }
    out << ");\n";
    return true;
}

int glyphIndex(char c)
{
    if (c >= 'A' && c <= 'Z') {
        return c - 'A';
    }
    if (c >= 'a' && c <= 'z') {
        return c - 'a';
    }
    return -1;
}

} // namespace

int main(int argc, char **argv)
{
    if (argc < 4) {
        std::fprintf(stderr, "usage: %s <font.ttf> <atlas.h> <metrics.glsl>\n", argv[0]);
        return 1;
    }

    const std::filesystem::path fontPath = argv[1];
    const std::filesystem::path atlasPath = argv[2];
    const std::filesystem::path metricsPath = argv[3];

    std::ifstream fontFile(fontPath, std::ios::binary);
    if (!fontFile) {
        std::fprintf(stderr, "failed to open font: %s\n", fontPath.string().c_str());
        return 1;
    }
    std::vector<uint8_t> fontData((std::istreambuf_iterator<char>(fontFile)), std::istreambuf_iterator<char>());

    stbtt_fontinfo font{};
    if (!stbtt_InitFont(&font, fontData.data(), stbtt_GetFontOffsetForIndex(fontData.data(), 0))) {
        std::fprintf(stderr, "stbtt_InitFont failed\n");
        return 1;
    }

    const float scale = stbtt_ScaleForPixelHeight(&font, kFontSize);
    int ascent = 0;
    int descent = 0;
    int lineGap = 0;
    stbtt_GetFontVMetrics(&font, &ascent, &descent, &lineGap);
    const int baseline = static_cast<int>(std::lround(ascent * scale));

    std::vector<uint8_t> atlas(static_cast<size_t>(kAtlasWidth * kAtlasHeight * 4), 0);
    GlyphRect glyphs[kGlyphCount]{};
    int penX = 2;

    for (int i = 0; i < kGlyphCount; ++i) {
        const char ch = static_cast<char>('A' + i);
        int advance = 0;
        int lsb = 0;
        stbtt_GetCodepointHMetrics(&font, ch, &advance, &lsb);

        int x0 = 0;
        int y0 = 0;
        int x1 = 0;
        int y1 = 0;
        stbtt_GetCodepointBitmapBox(&font, ch, scale, scale, &x0, &y0, &x1, &y1);

        const int gw = x1 - x0;
        const int gh = y1 - y0;
        if (penX + gw + 2 > kAtlasWidth) {
            std::fprintf(stderr, "atlas overflow at glyph %c\n", ch);
            return 1;
        }

        const int dstX = penX;
        const int dstY = baseline + y0;
        std::vector<uint8_t> bitmap(static_cast<size_t>(gw * gh), 0);
        stbtt_MakeCodepointBitmap(&font, bitmap.data(), gw, gh, gw, scale, scale, ch);

        for (int y = 0; y < gh; ++y) {
            for (int x = 0; x < gw; ++x) {
                const int ax = dstX + x;
                const int ay = dstY + y;
                if (ax < 0 || ay < 0 || ax >= kAtlasWidth || ay >= kAtlasHeight) {
                    continue;
                }
                const size_t idx = static_cast<size_t>((ay * kAtlasWidth + ax) * 4);
                const uint8_t a = bitmap[static_cast<size_t>(y * gw + x)];
                atlas[idx + 0] = 255;
                atlas[idx + 1] = 255;
                atlas[idx + 2] = 255;
                atlas[idx + 3] = a;
            }
        }

        glyphs[i].x0 = dstX;
        glyphs[i].y0 = dstY;
        glyphs[i].x1 = dstX + gw;
        glyphs[i].y1 = dstY + gh;
        glyphs[i].advance = advance * scale;
        penX += gw + 2;
    }

    if (!writeAtlasHeader(atlasPath, atlas)) {
        std::fprintf(stderr, "failed to write %s\n", atlasPath.string().c_str());
        return 1;
    }
    if (!writeMetricsGlsl(metricsPath, glyphs)) {
        std::fprintf(stderr, "failed to write %s\n", metricsPath.string().c_str());
        return 1;
    }
    return 0;
}
